import fs from 'fs';
let rules = fs.readFileSync('firestore.rules', 'utf8');

rules = rules.replace(
  "function isValidCampaign(data) {\n      return data.keys().hasAll(['userId', 'name', 'status', 'budget', 'spent', 'createdAt']) &&\n        data.userId == request.auth.uid &&\n        data.name is string && data.name.size() <= 200 &&\n        data.status is string && data.status.size() <= 50 &&\n        data.budget is number &&\n        data.spent is number &&\n        data.createdAt is number;\n    }",
  "function isValidCampaign(data) {\n      return data.keys().hasAll(['userId', 'name', 'status', 'type', 'createdAt']) &&\n        data.userId == request.auth.uid &&\n        data.name is string && data.name.size() <= 200 &&\n        data.status is string && data.status.size() <= 50 &&\n        data.type is string && data.type.size() <= 50 &&\n        data.createdAt is number;\n    }"
);

rules = rules.replace(
  "match /campaigns/{campaignId} {\n      allow get: if isSignedIn() && existing().userId == request.auth.uid;\n      allow list: if isSignedIn() && resource.data.userId == request.auth.uid;\n      allow create: if isSignedIn() && isValidId(campaignId) && isValidCampaign(incoming());\n      allow update: if isSignedIn() && existing().userId == request.auth.uid &&\n        incoming().userId == existing().userId &&\n        incoming().diff(existing()).affectedKeys().hasOnly(['status', 'spent']) &&\n        incoming().status is string && incoming().status.size() <= 50 &&\n        incoming().spent is number;\n      allow delete: if isSignedIn() && existing().userId == request.auth.uid;\n    }",
  "match /campaigns/{campaignId} {\n      allow get: if isSignedIn() && existing().userId == request.auth.uid;\n      allow list: if isSignedIn() && resource.data.userId == request.auth.uid;\n      allow create: if isSignedIn() && isValidId(campaignId) && isValidCampaign(incoming());\n      allow update: if isSignedIn() && existing().userId == request.auth.uid &&\n        incoming().userId == existing().userId &&\n        incoming().diff(existing()).affectedKeys().hasOnly(['status', 'type', 'name']) &&\n        incoming().status is string && incoming().status.size() <= 50 &&\n        incoming().type is string && incoming().type.size() <= 50 &&\n        incoming().name is string && incoming().name.size() <= 200;\n      allow delete: if isSignedIn() && existing().userId == request.auth.uid;\n    }\n\n    function isValidBlogResult(data) {\n      return data.keys().hasAll(['userId', 'campaignId', 'title', 'url', 'publishDate', 'views', 'createdAt']) &&\n        data.userId == request.auth.uid &&\n        data.campaignId is string &&\n        data.title is string && data.title.size() <= 200 &&\n        data.url is string && data.url.size() <= 1000 &&\n        data.publishDate is string && data.publishDate.size() <= 50 &&\n        data.views is number &&\n        data.createdAt is number;\n    }\n\n    match /blogResults/{resultId} {\n      allow get: if isSignedIn() && existing().userId == request.auth.uid;\n      allow list: if isSignedIn() && resource.data.userId == request.auth.uid;\n      allow create: if isSignedIn() && isValidId(resultId) && isValidBlogResult(incoming());\n      allow update: if isSignedIn() && existing().userId == request.auth.uid &&\n        incoming().userId == existing().userId &&\n        incoming().diff(existing()).affectedKeys().hasOnly(['title', 'url', 'publishDate', 'views']) &&\n        incoming().title is string && incoming().title.size() <= 200 &&\n        incoming().url is string && incoming().url.size() <= 1000 &&\n        incoming().publishDate is string && incoming().publishDate.size() <= 50 &&\n        incoming().views is number;\n      allow delete: if isSignedIn() && existing().userId == request.auth.uid;\n    }"
);

fs.writeFileSync('firestore.rules', rules);
